In [1]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting numpy>=1.22.0 (from scikit-learn)
  Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.2-cp313-cp313-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 926.6 kB/s eta 0:00:09
   ---- ----------------------------------- 1.0/8.7 MB 1.2 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/8.7 MB 1.2 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/8.7 MB 1.2 MB/s eta 0:00:07
   ------ --------------------------------- 1.3/8.7 MB 861.6 kB/s eta 0:00:09
   ------ --------------------------------- 1.3/8.7 MB 861.6 kB/s eta 0:00:09
   -------- ------------------------------- 1.8/8.7 MB 938.4 kB/s eta 0:00:08
   --------- ------------------------------ 2.1/8.7 MB 1.0 MB/s eta 0:00:07
   ---------- ----------------------------- 2.4/8.7 MB 1.1 MB/s eta 0:00:06
   ------------- -------------------------- 2.9/8.7 MB 1.2 MB/s eta 0:00:06
   -------------- ------------------------- 3.1/8.7 MB 1.2 MB/s eta 0:00:05
   --------------- ------------------------ 3.4/8.7 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.7/8.7 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.7/8.7 MB 1.2 MB/s eta 0:00:05
   ------------------- -------------------- 4.2/8.7 MB 1.2 MB/s eta 0:00:04
   -------------------- ------------------- 4.5/8.7 MB 1.2 MB/s eta 0:00:04
   --------------------- ------------------ 4.7/8.7 MB 1.2 MB/s eta 0:00:04
   ---------------------- ----------------- 5.0/8.7 MB 1.2 MB/s eta 0:00:04
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.2 MB/s eta 0:00:03
   ------------------------- -------------- 5.5/8.7 MB 953.6 kB/s eta 0:00:04
   -------------------------- ------------- 5.8/8.7 MB 970.4 kB/s eta 0:00:04
   -------------------------- ------------- 5.8/8.7 MB 970.4 kB/s eta 0:00:04
   --------------------------- ------------ 6.0/8.7 MB 952.2 kB/s eta 0:00:03
   ---------------------------- ----------- 6.3/8.7 MB 950.2 kB/s eta 0:00:03
   ------------------------------ --------- 6.6/8.7 MB 956.9 kB/s eta 0:00:03
   ------------------------------- -------- 6.8/8.7 MB 973.9 kB/s eta 0:00:02
   -------------------------------- ------- 7.1/8.7 MB 986.1 kB/s eta 0:00:02
   --------------------------------- ------ 7.3/8.7 MB 987.1 kB/s eta 0:00:02
   ---------------------------------- ----- 7.6/8.7 MB 981.9 kB/s eta 0:00:02
   ------------------------------------ --- 7.9/8.7 MB 990.7 kB/s eta 0:00:01
   ------------------------------------ --- 7.9/8.7 MB 990.7 kB/s eta 0:00:01
   ------------------------------------- -- 8.1/8.7 MB 989.5 kB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 995.9 kB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 997.5 kB/s  0:00:08
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Using cached numpy-2.3.3-cp313-cp313-win_amd64.whl (12.8 MB)
Downloading scipy-1.16.2-cp313-cp313-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
    --------------------------------------- 0.5/38.5 MB 1.2 MB/s eta 0:00:32
    --------------------------------------- 0.5/38.5 MB 1.2 MB/s eta 0:00:32
    --------------------------------------- 0.8/38.5 MB 1.0 MB/s eta 0:00:38
   - -------------------------------------- 1.0/38.5 MB 988.6 kB/s eta 0:00:38
   - -------------------------------------- 1.3/38.5 MB 1.0 MB/s eta 0:00:37
   - -------------------------------------- 1.3/38.5 MB 1.0 MB/s eta 0:00:37
   - -------------------------------------- 1.6/38.5 MB 911.9 kB/s eta 0:00:41
   - -------------------------------------- 1.8/38.5 MB 954.5 kB/s eta 0:00:39
   - -------------------------------------- 1.8/38.5 MB 954.5 kB/s eta 0:00:39
   - -------------------------------------- 1.8/38.5 MB 954.5 kB/s eta 0:00:39
   - -------------------------------------- 1.8/38.5 MB 954.5 kB/s eta 0:00:39
   - -------------------------------------- 1.8/38.5 MB 954.5 kB/s eta 0:00:39
   -- ------------------------------------- 2.1/38.5 MB 677.3 kB/s eta 0:00:54
   -- ------------------------------------- 2.4/38.5 MB 700.0 kB/s eta 0:00:52
   -- ------------------------------------- 2.6/38.5 MB 758.0 kB/s eta 0:00:48
   -- ------------------------------------- 2.9/38.5 MB 785.6 kB/s eta 0:00:46
   --- ------------------------------------ 3.1/38.5 MB 821.9 kB/s eta 0:00:44
   --- ------------------------------------ 3.7/38.5 MB 886.7 kB/s eta 0:00:40
   ---- ----------------------------------- 3.9/38.5 MB 915.1 kB/s eta 0:00:38
   ---- ----------------------------------- 4.2/38.5 MB 934.5 kB/s eta 0:00:37
   ---- ----------------------------------- 4.7/38.5 MB 1.0 MB/s eta 0:00:34
   ---- ----------------------------------- 4.7/38.5 MB 1.0 MB/s eta 0:00:34
   ----- ---------------------------------- 5.2/38.5 MB 1.0 MB/s eta 0:00:33
   ----- ---------------------------------- 5.8/38.5 MB 1.1 MB/s eta 0:00:31
   ------ --------------------------------- 6.0/38.5 MB 1.1 MB/s eta 0:00:30
   ------ --------------------------------- 6.6/38.5 MB 1.1 MB/s eta 0:00:28
   ------- -------------------------------- 6.8/38.5 MB 1.2 MB/s eta 0:00:28
   ------- -------------------------------- 7.1/38.5 MB 1.2 MB/s eta 0:00:27
   ------- -------------------------------- 7.3/38.5 MB 1.2 MB/s eta 0:00:27
   ------- -------------------------------- 7.6/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 7.9/38.5 MB 1.2 MB/s eta 0:00:27
   -------- ------------------------------- 8.1/38.5 MB 1.0 MB/s eta 0:00:30
   -------- ------------------------------- 8.1/38.5 MB 1.0 MB/s eta 0:00:30
   -------- ------------------------------- 8.4/38.5 MB 1.0 MB/s eta 0:00:31
   -------- ------------------------------- 8.4/38.5 MB 1.0 MB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   -------- ------------------------------- 8.7/38.5 MB 981.3 kB/s eta 0:00:31
   --------- ------------------------------ 8.9/38.5 MB 880.3 kB/s eta 0:00:34
   --------- ------------------------------ 9.2/38.5 MB 890.5 kB/s eta 0:00:33
   --------- ------------------------------ 9.2/38.5 MB 890.5 kB/s eta 0:00:33
   ---------- ----------------------------- 9.7/38.5 MB 893.5 kB/s eta 0:00:33
   ---------- ----------------------------- 9.7/38.5 MB 893.5 kB/s eta 0:00:33
   ---------- ----------------------------- 10.2/38.5 MB 911.0 kB/s eta 0:00:32
   ---------- ----------------------------- 10.5/38.5 MB 919.7 kB/s eta 0:00:31
   ----------- ---------------------------- 10.7/38.5 MB 933.9 kB/s eta 0:00:30
   ----------- ---------------------------- 10.7/38.5 MB 933.9 kB/s eta 0:00:30
   ----------- ---------------------------- 10.7/38.5 MB 933.9 kB/s eta 0:00:30
   ----------- ---------------------------- 10.7/38.5 MB 933.9 kB/s eta 0:00:30
   ----------- ---------------------------- 10.7/38.5 MB 933.9 kB/s eta 0:00:30
   ----------- ---------------------------- 11.0/38.5 MB 866.8 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/38.5 MB 866.8 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/38.5 MB 866.8 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/38.5 MB 866.8 kB/s eta 0:00:32
   ----------- ---------------------------- 11.0/38.5 MB 866.8 kB/s eta 0:00:32
   ----------- ---------------------------- 11.3/38.5 MB 826.3 kB/s eta 0:00:33
   ----------- ---------------------------- 11.3/38.5 MB 826.3 kB/s eta 0:00:33
   ----------- ---------------------------- 11.5/38.5 MB 818.8 kB/s eta 0:00:33
   ------------ --------------------------- 11.8/38.5 MB 817.9 kB/s eta 0:00:33
   ------------ --------------------------- 12.1/38.5 MB 825.9 kB/s eta 0:00:33
   ------------ --------------------------- 12.1/38.5 MB 825.9 kB/s eta 0:00:33
   ------------- -------------------------- 12.6/38.5 MB 837.0 kB/s eta 0:00:31
   ------------- -------------------------- 13.1/38.5 MB 858.3 kB/s eta 0:00:30
   ------------- -------------------------- 13.4/38.5 MB 867.7 kB/s eta 0:00:29
   ------------- -------------------------- 13.4/38.5 MB 867.7 kB/s eta 0:00:29
   -------------- ------------------------- 13.9/38.5 MB 874.0 kB/s eta 0:00:29
   -------------- ------------------------- 14.2/38.5 MB 881.8 kB/s eta 0:00:28
   -------------- ------------------------- 14.2/38.5 MB 881.8 kB/s eta 0:00:28
   -------------- ------------------------- 14.2/38.5 MB 881.8 kB/s eta 0:00:28
   -------------- ------------------------- 14.4/38.5 MB 864.3 kB/s eta 0:00:28
   -------------- ------------------------- 14.4/38.5 MB 864.3 kB/s eta 0:00:28
   --------------- ------------------------ 14.7/38.5 MB 859.9 kB/s eta 0:00:28
   --------------- ------------------------ 14.9/38.5 MB 865.3 kB/s eta 0:00:28
   --------------- ------------------------ 14.9/38.5 MB 865.3 kB/s eta 0:00:28
   --------------- ------------------------ 15.2/38.5 MB 857.0 kB/s eta 0:00:28
   ---------------- ----------------------- 15.7/38.5 MB 874.4 kB/s eta 0:00:27
   ---------------- ----------------------- 16.0/38.5 MB 881.6 kB/s eta 0:00:26
   ---------------- ----------------------- 16.3/38.5 MB 883.5 kB/s eta 0:00:26
   ---------------- ----------------------- 16.3/38.5 MB 883.5 kB/s eta 0:00:26
   ----------------- ---------------------- 16.5/38.5 MB 884.8 kB/s eta 0:00:25
   ----------------- ---------------------- 16.8/38.5 MB 885.2 kB/s eta 0:00:25
   ----------------- ---------------------- 17.0/38.5 MB 890.5 kB/s eta 0:00:25
   ----------------- ---------------------- 17.3/38.5 MB 891.2 kB/s eta 0:00:24
   ------------------ --------------------- 17.6/38.5 MB 893.9 kB/s eta 0:00:24
   ------------------ --------------------- 17.8/38.5 MB 899.0 kB/s eta 0:00:24
   ------------------ --------------------- 18.1/38.5 MB 905.6 kB/s eta 0:00:23
   ------------------- -------------------- 18.4/38.5 MB 909.6 kB/s eta 0:00:23
   ------------------- -------------------- 18.6/38.5 MB 912.5 kB/s eta 0:00:22
   ------------------- -------------------- 19.1/38.5 MB 926.4 kB/s eta 0:00:21
   -------------------- ------------------- 19.4/38.5 MB 933.6 kB/s eta 0:00:21
   -------------------- ------------------- 19.7/38.5 MB 938.1 kB/s eta 0:00:21
   -------------------- ------------------- 19.7/38.5 MB 938.1 kB/s eta 0:00:21
   -------------------- ------------------- 19.9/38.5 MB 927.6 kB/s eta 0:00:21
   -------------------- ------------------- 20.2/38.5 MB 933.1 kB/s eta 0:00:20
   -------------------- ------------------- 20.2/38.5 MB 933.1 kB/s eta 0:00:20
   --------------------- ------------------ 20.4/38.5 MB 924.0 kB/s eta 0:00:20
   --------------------- ------------------ 20.4/38.5 MB 924.0 kB/s eta 0:00:20
   --------------------- ------------------ 20.7/38.5 MB 921.2 kB/s eta 0:00:20
   --------------------- ------------------ 21.0/38.5 MB 926.5 kB/s eta 0:00:19
   --------------------- ------------------ 21.0/38.5 MB 926.5 kB/s eta 0:00:19
   --------------------- ------------------ 21.0/38.5 MB 926.5 kB/s eta 0:00:19
   --------------------- ------------------ 21.0/38.5 MB 926.5 kB/s eta 0:00:19
   --------------------- ------------------ 21.0/38.5 MB 926.5 kB/s eta 0:00:19
   ---------------------- ----------------- 21.8/38.5 MB 911.1 kB/s eta 0:00:19
   ---------------------- ----------------- 22.0/38.5 MB 921.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.3/38.5 MB 918.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.5/38.5 MB 920.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.5/38.5 MB 920.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.5/38.5 MB 920.7 kB/s eta 0:00:18
   ----------------------- ---------------- 22.8/38.5 MB 912.2 kB/s eta 0:00:18
   ----------------------- ---------------- 23.1/38.5 MB 913.6 kB/s eta 0:00:17
   ------------------------ --------------- 23.3/38.5 MB 915.5 kB/s eta 0:00:17
   ------------------------ --------------- 23.6/38.5 MB 921.9 kB/s eta 0:00:17
   ------------------------ --------------- 23.9/38.5 MB 924.7 kB/s eta 0:00:16
   ------------------------- -------------- 24.1/38.5 MB 925.5 kB/s eta 0:00:16
   ------------------------- -------------- 24.4/38.5 MB 924.1 kB/s eta 0:00:16
   ------------------------- -------------- 24.4/38.5 MB 924.1 kB/s eta 0:00:16
   ------------------------- -------------- 24.6/38.5 MB 923.8 kB/s eta 0:00:16
   ------------------------- -------------- 24.9/38.5 MB 927.2 kB/s eta 0:00:15
   -------------------------- ------------- 25.2/38.5 MB 924.7 kB/s eta 0:00:15
   -------------------------- ------------- 25.4/38.5 MB 927.7 kB/s eta 0:00:15
   -------------------------- ------------- 25.7/38.5 MB 931.3 kB/s eta 0:00:14
   --------------------------- ------------ 26.2/38.5 MB 941.5 kB/s eta 0:00:14
   --------------------------- ------------ 26.2/38.5 MB 941.5 kB/s eta 0:00:14
   --------------------------- ------------ 26.5/38.5 MB 943.0 kB/s eta 0:00:13
   ---------------------------- ----------- 27.0/38.5 MB 949.2 kB/s eta 0:00:13
   ---------------------------- ----------- 27.5/38.5 MB 959.4 kB/s eta 0:00:12
   ---------------------------- ----------- 27.8/38.5 MB 962.4 kB/s eta 0:00:12
   ----------------------------- ---------- 28.0/38.5 MB 967.3 kB/s eta 0:00:11
   ----------------------------- ---------- 28.3/38.5 MB 970.2 kB/s eta 0:00:11
   ----------------------------- ---------- 28.8/38.5 MB 977.5 kB/s eta 0:00:10
   ------------------------------ --------- 29.1/38.5 MB 980.6 kB/s eta 0:00:10
   ------------------------------ --------- 29.1/38.5 MB 980.6 kB/s eta 0:00:10
   ------------------------------ --------- 29.4/38.5 MB 980.1 kB/s eta 0:00:10
   ------------------------------ --------- 29.6/38.5 MB 974.6 kB/s eta 0:00:10
   ------------------------------ --------- 29.6/38.5 MB 974.6 kB/s eta 0:00:10
   ------------------------------- -------- 29.9/38.5 MB 970.3 kB/s eta 0:00:09
   ------------------------------- -------- 30.1/38.5 MB 974.9 kB/s eta 0:00:09
   ------------------------------- -------- 30.4/38.5 MB 979.5 kB/s eta 0:00:09
   ------------------------------- -------- 30.7/38.5 MB 980.4 kB/s eta 0:00:09
   ------------------------------- -------- 30.7/38.5 MB 980.4 kB/s eta 0:00:09
   ------------------------------- -------- 30.7/38.5 MB 980.4 kB/s eta 0:00:09
   -------------------------------- ------- 30.9/38.5 MB 970.4 kB/s eta 0:00:08
   -------------------------------- ------- 30.9/38.5 MB 970.4 kB/s eta 0:00:08
   -------------------------------- ------- 31.2/38.5 MB 990.6 kB/s eta 0:00:08
   -------------------------------- ------- 31.5/38.5 MB 989.3 kB/s eta 0:00:08
   -------------------------------- ------- 31.5/38.5 MB 989.3 kB/s eta 0:00:08
   -------------------------------- ------- 31.7/38.5 MB 990.0 kB/s eta 0:00:07
   --------------------------------- ------ 32.0/38.5 MB 988.3 kB/s eta 0:00:07
   --------------------------------- ------ 32.0/38.5 MB 988.3 kB/s eta 0:00:07
   --------------------------------- ------ 32.0/38.5 MB 988.3 kB/s eta 0:00:07
   --------------------------------- ------ 32.2/38.5 MB 964.4 kB/s eta 0:00:07
   ---------------------------------- ----- 32.8/38.5 MB 971.2 kB/s eta 0:00:06
   ---------------------------------- ----- 33.0/38.5 MB 966.5 kB/s eta 0:00:06
   ---------------------------------- ----- 33.6/38.5 MB 971.5 kB/s eta 0:00:06
   ---------------------------------- ----- 33.6/38.5 MB 971.5 kB/s eta 0:00:06
   ---------------------------------- ----- 33.6/38.5 MB 971.5 kB/s eta 0:00:06
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 33.8/38.5 MB 947.7 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ----------------------------------- ---- 34.1/38.5 MB 890.8 kB/s eta 0:00:05
   ------------------------------------ --- 34.9/38.5 MB 892.0 kB/s eta 0:00:05
   ------------------------------------ --- 35.1/38.5 MB 900.9 kB/s eta 0:00:04
   ------------------------------------ --- 35.4/38.5 MB 901.2 kB/s eta 0:00:04
   ------------------------------------- -- 35.7/38.5 MB 901.3 kB/s eta 0:00:04
   ------------------------------------- -- 35.9/38.5 MB 903.4 kB/s eta 0:00:03
   ------------------------------------- -- 36.2/38.5 MB 902.4 kB/s eta 0:00:03
   ------------------------------------- -- 36.4/38.5 MB 909.3 kB/s eta 0:00:03
   -------------------------------------- - 36.7/38.5 MB 913.3 kB/s eta 0:00:02
   -------------------------------------- - 37.0/38.5 MB 910.5 kB/s eta 0:00:02
   -------------------------------------- - 37.2/38.5 MB 913.0 kB/s eta 0:00:02
   -------------------------------------- - 37.5/38.5 MB 911.9 kB/s eta 0:00:02
   ---------------------------------------  37.7/38.5 MB 911.4 kB/s eta 0:00:01
   ---------------------------------------  38.0/38.5 MB 936.0 kB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 937.4 kB/s eta 0:00:01

In [4]:
pip install pandas

Collecting pandas
  Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\desktop\ai assignment\ml\env\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\desktop\ai assignment\ml\env\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\desktop\ai assignment\ml\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.2-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.2 pytz-2025.2 tzdata-2025.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install numpy

Requirement already satisfied: numpy in c:\users\lenovo\desktop\ai assignment\ml\env\lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
cars_data = pd.read_csv('cleaned_data.csv')

In [8]:
cars_data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,1,2014,450000,145500,1,1,1,1,23.40,1248.0,74.00,5.0
1,2,2014,370000,120000,1,1,1,2,21.14,1498.0,103.52,5.0
2,3,2006,158000,140000,2,1,1,3,17.70,1497.0,78.00,5.0
3,4,2010,225000,127000,1,1,1,1,23.00,1396.0,90.00,5.0
4,1,2007,130000,120000,2,1,1,1,16.10,1298.0,88.20,5.0

In [9]:
input_data = cars_data.drop(columns=['selling_price'])
output_data =cars_data['selling_price']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [11]:
#model Creation
model = LinearRegression()

In [12]:
#Train MOdel
model.fit(x_train, y_train)

LinearRegression()

In [13]:
predict = model.predict(x_test)

In [14]:
predict

array([  492782.52847838,   801150.46266122,  -408903.70304485, ...,
         625927.74445756, -2020987.9154586 ,   615410.39092368],
      shape=(1344,))

In [15]:
x_train.head(1)

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
6703,1,2017,12000,2,1,1,1,23.1,998.0,67.04,5.0

In [16]:
input_data_model = pd.DataFrame(
    [[5,2022,12000,1,1,1,1,12.99,2494.0,100.6,5.0]],
    columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats'])

In [17]:
input_data_model

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,5,2022,12000,1,1,1,1,12.99,2494.0,100.6,5.0

In [18]:
model.predict(input_data_model)

array([1092970.83846891])

In [19]:
import pickle as pk

In [20]:
pk.dump(model,open('model.pkl','wb'))

In [21]:
x_train.columns

Index(['name', 'year', 'km_driven', 'fuel', 'seller_type', 'transmission',
       'owner', 'mileage', 'engine', 'max_power', 'seats'],
      dtype='object')